import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ChevronDown, FileText, Printer, ShieldCheck } from 'lucide-react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { useStore } from '@/shared/store/useStore';
import { MotionGrid, MotionGridItem, MotionReveal } from '@/shared/motion/MotionPrimitives';

type Section = { title: string; paragraphs: string[] };
type Policy = { title: string; summary: string; sections: Section[] };
const common = {
  seller: ['VIP numbers are offered subject to live availability, successful payment, identity checks where required, and telecom eligibility. A displayed series tag describes cataloguing or origin only. Through Mobile Number Portability, an eligible buyer may port the number to another operator under applicable TRAI rules.', 'Prices, discounts, availability, and estimated activation or fulfilment information may change until an order is confirmed. We do not guarantee that every requested number, operator transfer, or activation will be completed by a telecom provider.'],
  liability: ['Services are provided with reasonable care, but indirect, incidental, special, or consequential loss is excluded to the extent permitted by law. Nothing excludes a consumer remedy, fraud liability, or another right that cannot lawfully be excluded.', 'Neither party is liable for delay caused by events beyond reasonable control, including telecom outages, regulatory actions, payment-network failures, natural events, or logistics disruption.'],
};
const POLICIES: Record<string, Policy> = {
  'terms-and-conditions': { title: 'Terms and Conditions', summary: 'Rules for using VIP Number World, buying numbers and accessories, payments, fulfilment, and responsible conduct.', sections: [
    { title: 'Acceptance and accounts', paragraphs: ['By accessing the platform or placing an order, you agree to these terms and the policies linked here. You must provide accurate information, protect your login credentials, and be legally capable of entering a contract.', 'We may suspend access used unlawfully, deceptively, to interfere with the platform, or to violate another person’s rights.'] },
    { title: 'VIP numbers and MNP', paragraphs: common.seller },
    { title: 'Accessories and orders', paragraphs: ['Accessories are sold as single-SKU products. Product images are representative of the listed item; colour or configuration differences are separate products. Stock is reserved for a limited payment window and an unpaid reservation may expire automatically.', 'A mixed order may contain number and accessory items. Number transfer and physical fulfilment progress independently even though they share an order and payment.'] },
    { title: 'Payments, pricing, and cancellation', paragraphs: ['Payments are processed through the displayed payment provider. Coupons apply only when accepted by the server. We may cancel and refund an order affected by incorrect pricing, fraud checks, unavailable inventory, or payment mismatch.', 'A pre-book cancellation request may be submitted within 48 hours of confirmed booking. Delivery, UPC, activation, or availability failures are reviewed for a full refund under the Refund Policy.'] },
    { title: 'Acceptable use and intellectual property', paragraphs: ['Do not scrape at harmful scale, probe security, automate purchases unfairly, upload malicious content, impersonate others, or use the service for unlawful communications. Platform software, branding, original copy, and design remain protected intellectual property.'] },
    { title: 'Disclaimers, liability, and force majeure', paragraphs: common.liability },
    { title: 'Law and disputes', paragraphs: ['These terms are governed by Indian law. Courts at the jurisdiction shown below have jurisdiction, subject to mandatory consumer forums and other statutory remedies. Please first contact support or the grievance officer so we can attempt an efficient resolution.'] },
  ]},
  'privacy-policy': { title: 'Privacy Policy', summary: 'How we collect, use, share, retain, and safeguard personal data in connection with our services.', sections: [
    { title: 'Data we collect', paragraphs: ['We collect account and contact details, shipping addresses, order and payment references, support communications, device and security logs, consent choices, wishlist/cart activity, and information required for number transfer or identity verification.', 'Payment credentials are handled by the payment provider; we normally receive transaction identifiers and status rather than complete card or bank credentials.'] },
    { title: 'Purposes and legal basis', paragraphs: ['We process data to provide requested services, fulfil orders, prevent fraud, secure accounts, provide support, meet tax and legal duties, improve the platform, and send marketing only where permitted. We limit collection to information reasonably necessary for those purposes.'] },
    { title: 'Sharing and processors', paragraphs: ['Data may be shared with payment providers, telecom or activation partners, delivery carriers, hosting and communications vendors, professional advisers, and public authorities where legally required. Vendors receive only what they need and are expected to protect it. We do not sell personal data.'] },
    { title: 'Retention and security', paragraphs: ['We retain information for the active service relationship and for applicable accounting, dispute, fraud-prevention, and statutory periods, then delete or anonymise it where practical. We use role-based access, encrypted transport, logging, and appropriate technical and organisational safeguards; no system can promise absolute security.'] },
    { title: 'Your choices and rights', paragraphs: ['Subject to applicable law, you may request access, correction, completion, erasure, consent withdrawal, and grievance resolution. We may verify identity and retain records required by law or needed to establish legal claims.', 'A person acting for a child or another individual must have valid authority. Please do not submit third-party identity information without permission.'] },
    { title: 'Contact and updates', paragraphs: ['Contact the grievance channel below for a privacy request. Material updates will be communicated through the platform or available contact details, and the effective date will be revised.'] },
  ]},
  'refund-policy': { title: 'Refund, Cancellation and Return Policy', summary: 'Eligibility and process for number refunds, pre-book cancellations, and issue-based accessory returns.', sections: [
    { title: 'VIP number and pre-book refunds', paragraphs: ['A pre-book cancellation request can be made within 48 hours after booking confirmation. A full-refund review is available when we cannot provide the number because of recorded delivery, UPC, activation, eligibility, or number-availability failure attributable to the fulfilment process.', 'Change of mind after the cancellation window, failed customer identity checks, an expired customer-supplied UPC, or a port rejected for customer-side eligibility may not qualify unless consumer law requires otherwise.'] },
    { title: 'Accessory issue returns', paragraphs: ['A request for a damaged, defective, or incorrect accessory must be submitted from the delivered order item within seven calendar days of recorded delivery. Include clear details and, where requested, photographs or unpacking evidence.', 'Returns are issue-based, not general change-of-mind returns. The item should be kept with original parts, packaging, and identifiers. We may arrange inspection, pickup, or diagnostic steps before approval.'] },
    { title: 'Refund or replacement resolution', paragraphs: ['Approved requests may receive replacement stock or a refund up to the affected accessory line value. A partial refund never includes unrelated VIP-number items. Duplicate and over-value refunds are prevented.', 'Refund timing after approval depends on Razorpay and the issuing bank. Replacement timing depends on stock and delivery availability.'] },
    { title: 'How to request help', paragraphs: ['Use the order-detail return control or contact support with the order number, affected item, reason, and evidence. This policy does not restrict remedies available under the Consumer Protection Act, 2019 or applicable e-commerce rules.'] },
  ]},
  'delivery-fulfilment-policy': { title: 'Delivery and Fulfilment Policy', summary: 'What to expect for physical accessory delivery and VIP-number transfer fulfilment.', sections: [
    { title: 'Accessory delivery', paragraphs: ['Delivery is free within serviceable locations in India for this release. A complete recipient name, Indian phone number, address lines, city, state, and postal code are required and stored as an order snapshot.', 'Tracking and carrier details are shown when available. Estimates are not guarantees; remote-area, weather, public holiday, carrier, or regulatory delays may apply.'] },
    { title: 'Number transfer and activation', paragraphs: ['Number fulfilment may require identity verification, a valid UPC, telecom eligibility, and completion of the operator’s MNP process. RTP means ready for the next transfer step, not guaranteed instant activation.', 'Accessory delivery and number transfer are tracked independently in a mixed order. One item’s fulfilment state does not automatically change another item.'] },
    { title: 'Delivery problems', paragraphs: ['Report damaged, incorrect, missing, or marked-delivered-but-not-received accessories promptly. Issue-return eligibility is measured from recorded delivery. If we cannot fulfil due to availability, delivery, UPC, or activation failure, we will review the affected amount for refund.'] },
  ]},
  'cookie-policy': { title: 'Cookie Policy', summary: 'How browser storage and similar technologies support sign-in, security, preferences, and measurement.', sections: [
    { title: 'Technologies used', paragraphs: ['We use essential cookies or local storage for sessions, cart and wishlist counts, theme, consent, and security. We may use limited analytics or performance technologies to understand aggregate use and diagnose errors.'] },
    { title: 'Your control', paragraphs: ['Essential storage is necessary for requested features. You can clear or block browser storage, but sign-in, checkout, remembered settings, and other functions may stop working. Where consent is legally required for non-essential technologies, controls will be provided.'] },
    { title: 'Third parties and updates', paragraphs: ['Payment, embedded communications, or other providers may set technologies under their own policies when you use those features. We update this policy when our technology or legal obligations materially change.'] },
  ]},
  'mnp-activation-policy': { title: 'MNP and Activation Policy', summary: 'The practical rules behind catalogued series tags, portability, UPC handling, and activation.', sections: [
    { title: 'Series tags are informational', paragraphs: ['Airtel, Jio, Vi, and BSNL labels describe the number’s catalogued series or origin. They are not a promise that the number must remain on that operator. Eligible customers may port to another operator through Mobile Number Portability.'] },
    { title: 'Customer responsibilities', paragraphs: ['You must provide accurate identity and telecom information, maintain eligibility, obtain and share a valid UPC when required, complete verification promptly, and follow operator instructions. TRAI and operator rules, including waiting periods or outstanding-dues conditions, may apply.'] },
    { title: 'Timelines and failures', paragraphs: ['RTP and activation estimates are operational guidance, not guarantees. Telecom providers control validation, porting, SIM issuance, and network activation. If fulfilment fails because of our number availability, delivery, UPC handling, or activation process, the affected order is eligible for full-refund review.'] },
    { title: 'Safety', paragraphs: ['Never share OTPs, passwords, or payment PINs with anyone claiming to complete activation. We may request lawful verification documents but will not ask for confidential banking authentication credentials.'] },
  ]},
  'disclaimer': { title: 'Disclaimer', summary: 'Important limits about numerology, availability, operator tags, third-party services, and informational content.', sections: [
    { title: 'Numerology', paragraphs: ['Numerology results, lucky-number suggestions, names, scores, and interpretations are provided for entertainment and personal preference. They are not financial, medical, legal, professional, or guaranteed predictive advice.'] },
    { title: 'Availability and third parties', paragraphs: ['Listings can change between browsing and transactional reservation. Operators, payment providers, carriers, and other third parties control parts of activation, payment, and delivery; their services may be interrupted or subject to separate terms.'] },
    { title: 'No unlawful use', paragraphs: ['A memorable number does not confer ownership of another party’s trade mark, identity, reputation, or communications. Buyers must use numbers lawfully and must not impersonate, harass, defraud, or mislead others.'] },
  ]},
  'grievance-redressal': { title: 'Grievance Redressal', summary: 'How to raise a complaint, what information to include, and how we manage escalations.', sections: [
    { title: 'Raise a grievance', paragraphs: ['Contact the grievance officer using the details below. Include your name and verified account contact, order or transaction reference, a clear description, supporting evidence, and the resolution requested. Do not email passwords, OTPs, or complete payment credentials.'] },
    { title: 'Acknowledgement and review', paragraphs: ['We will acknowledge and examine complaints within the periods required by applicable Indian law. Complex matters involving a carrier, operator, payment provider, fraud review, or additional evidence may take longer; we will communicate meaningful updates.'] },
    { title: 'Escalation and statutory remedies', paragraphs: ['If a response does not resolve the issue, reply requesting escalation and identify the unresolved point. Consumers may also use applicable consumer commissions or government grievance channels, and data principals retain remedies under applicable data-protection law.'] },
  ]},
};

export default function LegalPage({ policyKey }: { policyKey: keyof typeof POLICIES }) {
  const policy = POLICIES[policyKey]; const { site } = useStore(); const [open, setOpen] = useState<string[]>(policy.sections.map((s) => s.title));
  const reduceMotion = useReducedMotion();
  const effective = site.POLICY_EFFECTIVE_DATE || '17 August 2026';
  const identity = useMemo(() => ({ name: site.LEGAL_BUSINESS_NAME || site.SITE_TITLE || 'VIP Number World', email: site.LEGAL_EMAIL || site.CONTACT_EMAIL || 'support@vipnumberworld.com', address: site.LEGAL_REGISTERED_ADDRESS || site.SUPPORT_ADDRESS || 'India', jurisdiction: site.LEGAL_JURISDICTION || 'India', grievance: site.GRIEVANCE_OFFICER_NAME || 'Grievance Officer', grievanceEmail: site.GRIEVANCE_EMAIL || site.LEGAL_EMAIL || site.CONTACT_EMAIL || 'support@vipnumberworld.com' }), [site]);
  const toggle = (title: string) => setOpen((x) => x.includes(title) ? x.filter((v) => v !== title) : [...x,title]);
  return <div className="legal-page mx-auto max-w-7xl px-4 py-8">
    <MotionReveal><header className="public-page-hero rounded-2xl border border-primary/20 bg-gradient-to-br from-card via-card to-primary/10 p-5 sm:p-7"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><FileText className="h-5 w-5"/></div><h1 className="mt-4 text-3xl font-black sm:text-4xl">{policy.title}</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{policy.summary}</p><div className="mt-4 flex flex-wrap gap-1.5 text-[11px] font-bold text-muted-foreground"><span className="rounded-full border border-border bg-card px-2.5 py-1.5">Effective {effective}</span><span className="rounded-full border border-border bg-card px-2.5 py-1.5">India-focused draft</span><button onClick={() => window.print()} className="vnw-interactive inline-flex min-h-8 items-center gap-1.5 rounded-full border border-border bg-card px-2.5"><Printer className="h-3.5 w-3.5"/>Print</button></div></header></MotionReveal>
    <div className="mt-7 grid gap-7 lg:grid-cols-[260px_1fr]"><MotionReveal delay={.06} className="h-fit lg:sticky lg:top-24"><aside className="rounded-2xl border border-border bg-card p-4"><div className="mb-3 text-xs font-black uppercase tracking-wider text-primary">On this page</div><nav className="space-y-1">{policy.sections.map((s,i) => <a key={s.title} className="vnw-interactive block rounded-lg border border-transparent px-3 py-2 text-sm font-bold text-muted-foreground" href={`#section-${i+1}`}>{i+1}. {s.title}</a>)}</nav></aside></MotionReveal>
      <main className="space-y-4"><MotionGrid className="space-y-4">{policy.sections.map((s,i) => { const expanded = open.includes(s.title); return <MotionGridItem key={s.title}><section id={`section-${i+1}`} className="scroll-mt-28 overflow-hidden rounded-2xl border border-border bg-card transition-colors duration-200 hover:border-primary/45"><h2><button aria-expanded={expanded} onClick={() => toggle(s.title)} className="vnw-interactive flex min-h-14 w-full items-center justify-between gap-4 rounded-none border-0 p-5 text-left text-lg font-black focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary"><span>{i+1}. {s.title}</span><ChevronDown className={`h-5 w-5 shrink-0 transition-transform duration-200 ${expanded?'rotate-180':''}`}/></button></h2><AnimatePresence initial={false}>{expanded && <motion.div initial={reduceMotion?false:{opacity:0,y:-6}} animate={{opacity:1,y:0}} exit={reduceMotion?undefined:{opacity:0,y:-4}} transition={{duration:reduceMotion?0:.22}} className="space-y-4 border-t border-border px-5 py-5 text-sm leading-7 text-muted-foreground">{s.paragraphs.map((p) => <p key={p}>{p}</p>)}</motion.div>}</AnimatePresence></section></MotionGridItem>})}</MotionGrid>
        <section className="rounded-2xl border border-primary/25 bg-primary/5 p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck className="h-5 w-5 text-primary"/>Contact and legal identity</div><div className="mt-3 space-y-1 text-sm text-muted-foreground"><p>{identity.name}</p><p>{identity.address}</p><p>Jurisdiction: {identity.jurisdiction}</p><p>Legal contact: <a className="text-primary" href={`mailto:${identity.email}`}>{identity.email}</a></p><p>{identity.grievance}: <a className="text-primary" href={`mailto:${identity.grievanceEmail}`}>{identity.grievanceEmail}</a></p>{site.GSTIN && <p>GSTIN: {site.GSTIN}</p>}{site.CIN && <p>CIN: {site.CIN}</p>}</div></section>
        <p className="px-2 text-xs leading-5 text-muted-foreground">This is an operational legal draft and should be reviewed by qualified counsel before production publication. Reference frameworks: <a className="text-primary" href="https://www.meity.gov.in/documents/act-and-policies/digital-personal-data-protection-rules-2025-gDOxUjMtQWa" target="_blank" rel="noreferrer">DPDP Rules 2025</a>, <a className="text-primary" href="https://consumeraffairs.nic.in/acts-and-rules/consumer-protection/consumer-protection" target="_blank" rel="noreferrer">Consumer Protection material</a>, and <a className="text-primary" href="https://www.trai.gov.in/faqcategory/mobile-number-portability" target="_blank" rel="noreferrer">TRAI MNP guidance</a>.</p>
      </main></div>
  </div>;
}

export const legalPolicies = Object.keys(POLICIES);
