import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Check, ChevronRight, PackageCheck, RotateCcw, ShieldCheck, ShoppingCart, Truck } from 'lucide-react';
import { accessoryImageUrl, accessoriesAPI, cartAPI, type AccessoryProduct } from '@/core/api/vnwAPI';
import { formatINR } from '@/core/lib/format';
import { localService } from '@/core/services/local';
import { useStore } from '@/shared/store/useStore';
import { useToast } from '@/shared/hooks/use-toast';
import { EmptyState, Loader } from '@/shared/components/ui-bits';
import AccessoryCard from '@/shared/components/AccessoryCard';
import { MotionGrid, MotionGridItem, MotionReveal, MotionSection } from '@/shared/motion/MotionPrimitives';

export default function AccessoryDetail() {
  const { slug = '' } = useParams(); const navigate = useNavigate(); const { refreshCounts } = useStore(); const { toast } = useToast();
  const [product, setProduct] = useState<AccessoryProduct | null>(null); const [related,setRelated]=useState<AccessoryProduct[]>([]); const [active, setActive] = useState<number | null>(null); const [quantity, setQuantity] = useState(1); const [loading, setLoading] = useState(true);
  useEffect(() => { accessoriesAPI.detail(slug).then(async(p) => { setProduct(p); setActive(p.images?.[0]?.image_id || p.primary_image_id || null); try{const list=await accessoriesAPI.list({category:p.category,limit:5});setRelated(list.items.filter(x=>x.accessory_id!==p.accessory_id).slice(0,4));}catch{setRelated([]);} }).catch(() => setProduct(null)).finally(() => setLoading(false)); }, [slug]);
  const add = async (buy = false) => { if (!product) return; if (!localService.getToken()) return navigate(`/login?next=${encodeURIComponent(location.pathname)}`); try { if (buy) navigate(`/checkout?accessory_id=${product.accessory_id}&quantity=${quantity}`); else { await cartAPI.addAccessory(product.accessory_id, quantity); await refreshCounts(); toast({ title: 'Added to cart' }); } } catch (e: any) { toast({ title: 'Could not continue', description: e.message, variant: 'destructive' }); } };
  if (loading) return <div className="py-24"><Loader/></div>; if (!product) return <div className="mx-auto max-w-4xl px-4 py-16"><EmptyState title="Product not found" action={<Link className="btn-gold" to="/accessories">Browse accessories</Link>}/></div>;
  return <div className="mx-auto max-w-7xl px-4 py-7 pb-24 lg:pb-8">
    <nav className="mb-5 flex flex-wrap items-center gap-1 text-xs text-muted-foreground"><Link to="/accessories">Accessories</Link><ChevronRight className="h-3 w-3"/>{product.category || 'Mobile accessory'}<ChevronRight className="h-3 w-3"/>{product.brand}</nav>
    <div className="grid gap-8 lg:grid-cols-[minmax(0,1.05fr)_minmax(360px,.95fr)]">
      <MotionReveal className="lg:sticky lg:top-24 lg:self-start"><section><div className="aspect-square overflow-hidden rounded-[2rem] border border-border bg-card">{active ? <img src={accessoryImageUrl(active)} alt={product.name} className="h-full w-full object-contain p-6"/> : <span className="grid h-full place-items-center"><PackageCheck className="h-24 w-24 text-primary/30"/></span>}</div>{!!product.images?.length && <div className="mt-3 flex gap-3 overflow-x-auto pb-2">{product.images.map((img) => <button aria-label={`View ${img.alt_text || product.name}`} key={img.image_id} onClick={() => setActive(img.image_id)} className={`h-20 w-20 shrink-0 overflow-hidden rounded-xl border bg-card ${active === img.image_id ? 'border-primary ring-2 ring-primary/20' : 'border-border'}`}><img src={accessoryImageUrl(img.image_id)} alt="" className="h-full w-full object-contain p-1"/></button>)}</div>}</section></MotionReveal>
      <MotionReveal delay={.08}><section><div className="text-xs font-black uppercase tracking-[.2em] text-primary">{product.brand}{product.model ? ` · ${product.model}` : ''}</div><h1 className="mt-2 text-3xl font-black leading-tight text-foreground">{product.name}</h1><p className="mt-3 text-muted-foreground">{product.short_description}</p><div className="my-5 h-px bg-border"/>
        <div className="flex flex-wrap items-baseline gap-3"><span className="text-3xl font-black">{formatINR(product.offer_price)}</span>{product.mrp > product.offer_price && <><span className="text-sm text-muted-foreground line-through">MRP {formatINR(product.mrp)}</span><span className="rounded-full bg-success/10 px-2 py-1 text-xs font-black text-success">Save {product.discount_pct}%</span></>}</div><p className="mt-1 text-xs text-muted-foreground">Inclusive of all taxes</p>
        <div className="mt-5 grid gap-3 sm:grid-cols-3">{[[Truck,'Free delivery'],[ShieldCheck,product.warranty || 'Secure purchase'],[RotateCcw,'7-day issue support']].map(([Icon,label]: any) => <div key={label} className="rounded-xl border border-border bg-card p-3 text-center text-xs font-bold"><Icon className="mx-auto mb-2 h-5 w-5 text-primary"/>{label}</div>)}</div>
        {!!product.highlights?.length && <div className="mt-6"><h2 className="font-black">Highlights</h2><ul className="mt-3 space-y-2">{product.highlights.map((x) => <li key={x} className="flex gap-2 text-sm text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-success"/>{x}</li>)}</ul></div>}
        <div className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-4"><div className="font-black text-success">In stock</div><label className="mt-3 flex items-center gap-3 text-sm font-bold">Quantity <select className="min-h-11 rounded-xl border border-border bg-card px-3" value={quantity} onChange={(e) => setQuantity(Number(e.target.value))}>{Array.from({length: Math.min(10,product.available_stock)},(_,i) => i+1).map((n) => <option key={n}>{n}</option>)}</select></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={() => add()} className="btn-gold-outline min-h-12"><ShoppingCart className="h-4 w-4"/>Add to cart</button><button onClick={() => add(true)} className="btn-gold min-h-12">Buy now</button></div></div>
        {product.description && <div className="mt-7"><h2 className="text-xl font-black">Product description</h2><p className="mt-3 whitespace-pre-line leading-7 text-muted-foreground">{product.description}</p></div>}
        {!!product.specifications?.length && <div className="mt-7"><h2 className="text-xl font-black">Specifications</h2><dl className="mt-3 overflow-hidden rounded-2xl border border-border">{product.specifications.map((s,i) => <div key={s.label} className={`grid grid-cols-[140px_1fr] gap-3 p-3 text-sm ${i%2?'bg-muted/40':'bg-card'}`}><dt className="font-bold">{s.label}</dt><dd className="text-muted-foreground">{s.value}</dd></div>)}</dl></div>}
        <p className="mt-7 text-xs text-muted-foreground">Returns are accepted for damaged, defective, or incorrect products when requested within seven days of recorded delivery. See our <Link to="/refund-policy" className="font-bold text-primary">Refund Policy</Link>.</p>
      </section></MotionReveal>
    </div>
    {related.length>0&&<MotionSection className="mt-12 border-t border-border pt-8"><h2 className="text-2xl font-black">Related accessories</h2><MotionGrid className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{related.map(p=><MotionGridItem key={p.accessory_id}><AccessoryCard product={p}/></MotionGridItem>)}</MotionGrid></MotionSection>}
    <div className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-2 gap-2 border-t border-border bg-card/95 p-3 backdrop-blur lg:hidden"><button onClick={() => add()} className="btn-gold-outline min-h-12">Add to cart</button><button onClick={() => add(true)} className="btn-gold min-h-12">Buy now</button></div>
  </div>;
}
