import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react';
import { adminAPI } from '@/core/api/vnwAPI';
import { useToast } from '@/shared/hooks/use-toast';
import { Loader, Money, PageHeader, StatusBadge, Table } from '@/shared/components/ui-bits';

export default function AdminHomePremium(){const {toast}=useToast();const [selected,setSelected]=useState<any[]>([]);const [catalog,setCatalog]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [q,setQ]=useState('');
  const load=async()=>{setLoading(true);try{const [s,c]=await Promise.all([adminAPI.homePremiumList(),adminAPI.numbersList({q,status:'AVAILABLE',limit:60})]);setSelected(s||[]);setCatalog(c.items||[]);}catch(e:any){toast({title:'Could not load premium manager',description:e.message,variant:'destructive'});}finally{setLoading(false);}};useEffect(()=>{load();},[]);
  const move=async(i:number,d:number)=>{const next=[...selected],j=i+d;if(j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];setSelected(next);await adminAPI.homePremiumReorder(next.map(x=>Number(x.homepage_premium_id)));};
  return <div><PageHeader title="Premium Homepage" subtitle="Select stored numbers, publish or hide them, and control exact homepage order"/><div className="mb-5 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm text-muted-foreground">Only selected, published, available numbers with stock are shown. Ineligible items stay saved in this order and reappear when eligible.</div>{loading?<Loader/>:<div className="grid gap-6 xl:grid-cols-2"><section><h2 className="mb-3 text-lg font-black">Homepage order</h2><div className="space-y-2">{selected.map((n,i)=><div key={n.homepage_premium_id} className="flex items-center gap-3 rounded-xl border border-border bg-card p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-primary/10 text-xs font-black text-primary">{i+1}</span><div className="flex-1"><b>{n.display_number}</b><div className="text-xs text-muted-foreground">{n.operator||'Unassigned'} · {n.status} · stock {n.stock}</div></div><label className="text-xs"><input type="checkbox" checked={!!n.homepage_active} onChange={async e=>{await adminAPI.homePremiumSave({homepage_premium_id:n.homepage_premium_id,number_id:n.number_id,is_active:e.target.checked});load();}}/> Published</label><button className="h-11 w-9" onClick={()=>move(i,-1)}><ArrowUp className="h-4 w-4"/></button><button className="h-11 w-9" onClick={()=>move(i,1)}><ArrowDown className="h-4 w-4"/></button><button className="h-11 w-9 text-destructive" onClick={async()=>{await adminAPI.homePremiumRemove(n.homepage_premium_id);load();}}><Trash2 className="h-4 w-4"/></button></div>)}</div></section><section><div className="mb-3 flex items-center gap-2"><input className="min-h-11 flex-1 rounded-xl border border-border bg-card px-3 text-sm" placeholder="Search stored numbers" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn-gold-outline" onClick={load}>Search</button></div><Table head={['Number','Series','Price','']} >{catalog.map(n=><tr key={n.number_id} className="border-b border-border"><td className="px-4 py-3"><b>{n.display_number}</b><br/><StatusBadge status={n.status}/></td><td className="px-4 py-3 text-xs">{n.operator||'Unassigned'}</td><td className="px-4 py-3"><Money value={n.offer_price}/></td><td className="px-4 py-3"><button disabled={selected.some(x=>x.number_id===n.number_id)} className="btn-gold-outline text-xs disabled:opacity-40" onClick={async()=>{await adminAPI.homePremiumSave({number_id:n.number_id,is_active:true});load();}}><Plus className="h-3 w-3"/>Select</button></td></tr>)}</Table></section></div>}</div>;
}
