import { useEffect, useState } from 'react';
import { Archive, ArrowDown, ArrowUp, Home, ImagePlus, Pencil, Plus, RotateCcw, Trash2 } from 'lucide-react';
import { accessoryImageUrl, adminAPI, type AccessoryProduct } from '@/core/api/vnwAPI';
import { useToast } from '@/shared/hooks/use-toast';
import { Loader, Money, PageHeader, StatusBadge, Table } from '@/shared/components/ui-bits';
import Modal from '@/shared/components/Modal';
import AccessoryImageCropper from './components/AccessoryImageCropper';

const empty: any = { name:'',brand:'',model:'',sku:'',category:'',mrp:'',offer_price:'',stock:0,short_description:'',description:'',highlights:'',specifications:'',warranty:'',status:'DRAFT' };
function ImageOrdering({ accessoryId, images, setImages }: { accessoryId:number; images:any[]; setImages:(images:any[])=>void }) {
  const persist=async(next:any[],primaryId:number)=>{setImages(next);await adminAPI.accessoryImagesReorder(accessoryId,next.map(x=>x.image_id),primaryId);};
  const move=(index:number,delta:number)=>{const target=index+delta;if(target<0||target>=images.length)return;const next=[...images];[next[index],next[target]]=[next[target],next[index]];persist(next,Number(next.find(x=>Number(x.is_primary))?.image_id||next[0]?.image_id));};
  return <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{images.map((img:any,index:number)=><div key={img.image_id} className={`overflow-hidden rounded-xl border bg-card p-2 ${Number(img.is_primary)?'border-primary ring-2 ring-primary/20':'border-border'}`}><img src={accessoryImageUrl(img.image_id)} className="aspect-square w-full rounded-lg bg-muted object-cover" alt={img.alt_text||''}/><div className="mt-2 grid grid-cols-4 gap-1"><button type="button" aria-label="Move image left" className="grid h-9 place-items-center" onClick={()=>move(index,-1)}><ArrowUp className="h-4 w-4 -rotate-90"/></button><button type="button" aria-label="Move image right" className="grid h-9 place-items-center" onClick={()=>move(index,1)}><ArrowDown className="h-4 w-4 -rotate-90"/></button><button type="button" aria-label="Make primary image" title="Make primary" className="grid h-9 place-items-center text-primary" onClick={()=>persist(images.map(x=>({...x,is_primary:x.image_id===img.image_id?1:0})),img.image_id)}><Home className="h-4 w-4"/></button><button type="button" aria-label="Delete image" className="grid h-9 place-items-center text-destructive" onClick={async()=>{await adminAPI.accessoryImageDelete(img.image_id);setImages(images.filter(x=>x.image_id!==img.image_id));}}><Trash2 className="h-4 w-4"/></button></div></div>)}</div>;
}
export default function AdminAccessories() {
  const { toast } = useToast(); const [tab,setTab]=useState<'catalog'|'home'|'returns'>('catalog'); const [items,setItems]=useState<AccessoryProduct[]>([]); const [home,setHome]=useState<AccessoryProduct[]>([]); const [returns,setReturns]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>(empty); const [images,setImages]=useState<any[]>([]); const [uploadingImages,setUploadingImages]=useState(false); const [cropFiles,setCropFiles]=useState<File[]>([]);
  const load=async()=>{setLoading(true);try{const [catalog,featured,requests]=await Promise.all([adminAPI.accessoriesList({q,limit:60}),adminAPI.homeAccessoriesList(),adminAPI.accessoryReturnsList()]);setItems(catalog.items||[]);setHome(featured||[]);setReturns(requests||[]);}catch(e:any){toast({title:'Could not load accessories',description:e.message,variant:'destructive'});}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const edit=async(p?:AccessoryProduct)=>{if(!p){setForm(empty);setImages([]);setOpen(true);return;}try{const d=await adminAPI.accessoryDetail(p.accessory_id);setForm({...d,highlights:(d.highlights||[]).join('\n'),specifications:(d.specifications||[]).map(x=>`${x.label}: ${x.value}`).join('\n')});setImages(d.images||[]);setOpen(true);}catch(e:any){toast({title:'Could not open product',description:e.message,variant:'destructive'});}};
  const save=async(e:React.FormEvent)=>{e.preventDefault();try{const d=await adminAPI.accessorySave({...form,mrp:Number(form.mrp),offer_price:Number(form.offer_price),stock:Number(form.stock)});toast({title:'Accessory saved'});if(!form.accessory_id){setForm({...form,accessory_id:d.accessory_id});}await load();}catch(e:any){toast({title:'Save failed',description:e.message,variant:'destructive'});}};
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{
    const input=e.target; const files=Array.from(input.files||[]); input.value='';
    if(!files.length||!form.accessory_id)return;
    const remaining=8-images.length;
    if(remaining<=0){toast({title:'Image limit reached',description:'An accessory can contain up to 8 images.',variant:'destructive'});return;}
    if(files.length>remaining){toast({title:'Too many images',description:`Choose up to ${remaining} more image${remaining===1?'':'s'}.`,variant:'destructive'});return;}
    if(files.some(file=>file.size>8*1024*1024)){toast({title:'Image is too large',description:'Each image must be 8 MB or smaller.',variant:'destructive'});return;}
    setCropFiles(files);
  };
  const uploadCropped=async(files:File[])=>{
    setUploadingImages(true);
    try{const result=await adminAPI.accessoryImagesUpload(form.accessory_id,files,form.name);const d=await adminAPI.accessoryDetail(form.accessory_id);setImages(d.images||[]);const duplicateText=result?.duplicates?` ${result.duplicates} duplicate${result.duplicates===1?' was':'s were'} skipped.`:'';toast({title:`${result?.uploaded||0} image${result?.uploaded===1?'':'s'} uploaded`,description:duplicateText.trim()||undefined});}
    catch(err:any){toast({title:'Upload failed',description:err.message,variant:'destructive'});}finally{setUploadingImages(false);setCropFiles([]);}
  };
  const addHome=async(id:number)=>{try{await adminAPI.homeAccessorySave({accessory_id:id,is_active:true});toast({title:'Added to homepage'});load();}catch(e:any){toast({title:'Could not add',description:e.message,variant:'destructive'});}};
  const move=async(index:number,delta:number)=>{const next=[...home];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setHome(next);await adminAPI.homeAccessoriesReorder(next.map(x=>Number(x.homepage_accessory_id)));};
  const resolve=async(id:number,resolution:string)=>{try{const approve=resolution!=='REJECTED';await adminAPI.accessoryReturnResolve({return_request_id:id,approve,admin_note:approve?'Approved after review':'Rejected after review'});toast({title:'Return updated'});load();}catch(e:any){toast({title:'Resolution failed',description:e.message,variant:'destructive'});}};
  const input='min-h-11 w-full rounded-xl border border-border bg-secondary px-3 text-sm outline-none focus:border-primary';
  return <div><PageHeader title="Accessories" subtitle="Manage products, homepage selection, stock, fulfilment-ready catalog, and returns" action={<button onClick={()=>edit()} className="btn-gold"><Plus className="h-4 w-4"/>New product</button>}/>
    <div className="mb-5 flex flex-wrap gap-2">{([['catalog','Catalog'],['home','Homepage Showcase'],['returns','Returns Queue']] as const).map(([k,label])=><button key={k} onClick={()=>setTab(k)} className={tab===k?'btn-gold min-h-11':'btn-gold-outline min-h-11'}>{label}</button>)}</div>
    {loading?<Loader/>:tab==='catalog'?<><div className="mb-4 flex gap-2"><input className={input} placeholder="Search products, brands, models or SKU" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn-gold-outline" onClick={load}>Search</button></div><Table head={['Product','Brand / SKU','Price','Stock','Status','Actions']}>
      {items.map(p=><tr key={p.accessory_id} className="border-b border-border"><td className="px-4 py-3"><div className="flex items-center gap-3">{p.primary_image_id?<img className="h-12 w-12 rounded-lg border border-border object-contain" src={accessoryImageUrl(p.primary_image_id)} alt=""/>:<div className="h-12 w-12 rounded-lg bg-muted"/>}<b>{p.name}</b></div></td><td className="px-4 py-3 text-xs text-muted-foreground">{p.brand} · {p.model}<br/>{p.sku}</td><td className="px-4 py-3"><Money value={p.offer_price}/></td><td className="px-4 py-3">{p.available_stock}/{p.stock}</td><td className="px-4 py-3"><StatusBadge status={p.status}/></td><td className="px-4 py-3"><div className="flex gap-3"><button title="Edit" onClick={()=>edit(p)}><Pencil className="h-4 w-4"/></button><button title="Show on home" onClick={()=>addHome(p.accessory_id)}><Home className="h-4 w-4 text-primary"/></button><button title="Archive" onClick={async()=>{if(confirm('Archive this product?')){await adminAPI.accessoryArchive(p.accessory_id);load();}}}><Archive className="h-4 w-4 text-destructive"/></button></div></td></tr>)}
    </Table></>:tab==='home'?<div className="space-y-3">{!home.length&&<p className="rounded-xl border border-dashed border-border p-8 text-center text-muted-foreground">No products selected. Use the home icon in Catalog.</p>}{home.map((p,i)=><div key={p.homepage_accessory_id} className="flex flex-wrap items-center gap-3 rounded-xl border border-border bg-card p-3">{p.primary_image_id&&<img src={accessoryImageUrl(p.primary_image_id)} className="h-14 w-14 rounded-lg object-contain" alt=""/>}<div className="min-w-0 flex-1"><b>{p.name}</b><div className="text-xs text-muted-foreground">{p.status} · {p.available_stock} available</div></div><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={!!p.homepage_active} onChange={async e=>{await adminAPI.homeAccessorySave({homepage_accessory_id:p.homepage_accessory_id,accessory_id:p.accessory_id,is_active:e.target.checked});load();}}/>Published</label><button onClick={()=>move(i,-1)} className="grid h-11 w-11 place-items-center"><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(i,1)} className="grid h-11 w-11 place-items-center"><ArrowDown className="h-4 w-4"/></button><button onClick={async()=>{await adminAPI.homeAccessoryRemove(Number(p.homepage_accessory_id));load();}} className="grid h-11 w-11 place-items-center text-destructive"><Trash2 className="h-4 w-4"/></button></div>)}</div>:<Table head={['Request','Order / Product','Reason','Resolution','Status','Actions']}>{returns.map(r=><tr key={r.return_request_id} className="border-b border-border"><td className="px-4 py-3">#{r.return_request_id}</td><td className="px-4 py-3 text-xs">{r.order_no}<br/><b>{r.name}</b></td><td className="px-4 py-3 text-xs">{r.reason}<br/>{r.details}</td><td className="px-4 py-3">{r.requested_resolution}</td><td className="px-4 py-3"><StatusBadge status={r.status}/></td><td className="px-4 py-3"><div className="flex gap-2"><button className="btn-gold-outline text-xs" onClick={()=>resolve(r.return_request_id,'REJECTED')}>Reject</button><button className="btn-gold text-xs" onClick={()=>resolve(r.return_request_id,r.requested_resolution==='REPLACEMENT'?'REPLACEMENT_APPROVED':'REFUND_APPROVED')}>{r.requested_resolution==='REPLACEMENT'?<RotateCcw className="h-3 w-3"/>:null}Approve</button></div></td></tr>)}</Table>}
    <Modal open={open} onClose={()=>setOpen(false)} title={form.accessory_id?'Edit accessory':'Create accessory'} wide><form onSubmit={save} className="grid gap-3 sm:grid-cols-2">{[['name','Name'],['brand','Brand'],['model','Model'],['sku','SKU'],['category','Category'],['warranty','Warranty']].map(([k,l])=><label key={k} className="text-xs font-bold text-muted-foreground">{l}<input required={['name','brand','sku'].includes(k)} className={input} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}{[['mrp','MRP'],['offer_price','Offer price'],['stock','Stock']].map(([k,l])=><label key={k} className="text-xs font-bold text-muted-foreground">{l}<input type="number" min="0" required className={input} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="text-xs font-bold text-muted-foreground">Status<select className={input} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['DRAFT','ACTIVE','INACTIVE','ARCHIVED'].map(x=><option key={x}>{x}</option>)}</select></label><label className="sm:col-span-2 text-xs font-bold text-muted-foreground">Short description<input className={input} value={form.short_description||''} onChange={e=>setForm({...form,short_description:e.target.value})}/></label><label className="sm:col-span-2 text-xs font-bold text-muted-foreground">Description<textarea rows={4} className={input+' py-3'} value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="text-xs font-bold text-muted-foreground">Highlights (one per line)<textarea rows={5} className={input+' py-3'} value={form.highlights||''} onChange={e=>setForm({...form,highlights:e.target.value})}/></label><label className="text-xs font-bold text-muted-foreground">Specifications (Label: Value)<textarea rows={5} className={input+' py-3'} value={form.specifications||''} onChange={e=>setForm({...form,specifications:e.target.value})}/></label><button className="btn-gold sm:col-span-2">Save product</button></form>
      {form.accessory_id&&<div className="mt-6 border-t border-border pt-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">Product images</h3><p className="mt-1 text-xs text-muted-foreground">{images.length}/8 uploaded · Every selected image is cropped to the same 1:1 product frame.</p></div><label aria-disabled={uploadingImages||images.length>=8} className={`btn-gold-outline cursor-pointer ${uploadingImages||images.length>=8?'pointer-events-none opacity-50':''}`}><ImagePlus className="h-4 w-4"/>{uploadingImages?'Uploading…':'Select & crop images'}<input hidden multiple type="file" accept="image/png,image/jpeg,image/webp" disabled={uploadingImages||images.length>=8} onChange={upload}/></label></div><ImageOrdering accessoryId={form.accessory_id} images={images} setImages={setImages}/></div>}
    </Modal>
    {!!cropFiles.length&&<AccessoryImageCropper files={cropFiles} onCancel={()=>setCropFiles([])} onComplete={uploadCropped}/>}
  </div>;
}
