import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Handshake, ImageUp, Pencil, Plus, Trash2 } from 'lucide-react';
import { adminAPI, siteAPI, type TrustedClient } from '@/core/api/vnwAPI';
import { useToast } from '@/shared/hooks/use-toast';
import { EmptyState, Loader, PageHeader, StatusBadge } from '@/shared/components/ui-bits';
import Modal from '@/shared/components/Modal';

const blank: Partial<TrustedClient> = { name: '', website_url: '', alt_text: '', is_active: true };
const field = 'w-full rounded-xl border border-border bg-card px-3 py-2.5 text-sm text-foreground outline-none focus:border-primary focus:ring-2 focus:ring-primary/15';

export default function AdminTrustedClients() {
  const { toast } = useToast();
  const fileRef = useRef<HTMLInputElement>(null);
  const [items, setItems] = useState<TrustedClient[]>([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<Partial<TrustedClient>>(blank);
  const [file, setFile] = useState<File | null>(null);
  const load = () => { setLoading(true); adminAPI.trustedClientsList().then(setItems).catch((e) => toast({ title: 'Unable to load clients', description: e.message, variant: 'destructive' })).finally(() => setLoading(false)); };
  useEffect(load, []);
  const edit = (item?: TrustedClient) => { setForm(item ? { ...item } : blank); setFile(null); setOpen(true); };
  const save = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); try { const saved = await adminAPI.trustedClientSave(form); const id = Number(form.client_id || saved.client_id); if (file) await adminAPI.trustedClientLogoUpload(id, file); toast({ title: 'Trusted client saved' }); setOpen(false); load(); } catch (error: any) { toast({ title: 'Could not save client', description: error.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const remove = async (item: TrustedClient) => { if (!window.confirm(`Delete ${item.name}?`)) return; try { await adminAPI.trustedClientDelete(item.client_id); load(); } catch (e: any) { toast({ title: 'Could not delete client', description: e.message, variant: 'destructive' }); } };
  const move = async (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= items.length) return; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; setItems(next); try { await adminAPI.trustedClientsReorder(next.map((x) => x.client_id)); } catch (e: any) { toast({ title: 'Could not reorder', description: e.message, variant: 'destructive' }); load(); } };

  return <div><PageHeader title="Trusted Clients" subtitle="Publish authentic client logos shown on the storefront" action={<button onClick={() => edit()} className="btn-gold"><Plus className="h-4 w-4" /> Add Client</button>} />
    <div className="mb-5 rounded-xl border border-primary/20 bg-primary/10 p-4 text-sm text-foreground"><div className="flex gap-3"><Handshake className="h-5 w-5 shrink-0 text-primary" /><p>Only publish organizations that have approved the use of their name and logo. Inactive records never appear publicly.</p></div></div>
    {loading ? <Loader /> : !items.length ? <EmptyState title="No trusted clients yet" description="Add approved client logos when they are ready." action={<button onClick={() => edit()} className="btn-gold">Add client</button>} /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item, index) => <article key={item.client_id} className="rounded-2xl border border-border bg-card p-4 shadow-sm"><div className="grid min-h-24 place-items-center rounded-xl bg-background p-3">{item.has_logo ? <img src={siteAPI.trustedClientLogoUrl(item.client_id)} alt={item.alt_text || item.name} className="max-h-14 max-w-[180px] object-contain" /> : <ImageUp className="h-8 w-8 text-muted-foreground" />}</div><div className="mt-3 flex items-start justify-between gap-2"><div><h2 className="font-black text-foreground">{item.name}</h2><StatusBadge status={item.is_active ? 'ACTIVE' : 'INACTIVE'} /></div><div className="flex gap-1"><button onClick={() => move(index, -1)} disabled={!index} className="grid h-8 w-8 place-items-center rounded-lg border border-border disabled:opacity-30"><ArrowUp className="h-4 w-4" /></button><button onClick={() => move(index, 1)} disabled={index === items.length - 1} className="grid h-8 w-8 place-items-center rounded-lg border border-border disabled:opacity-30"><ArrowDown className="h-4 w-4" /></button></div></div><div className="mt-4 flex justify-end gap-2"><button onClick={() => edit(item)} className="btn-gold-outline min-h-9 px-3 text-xs"><Pencil className="h-3.5 w-3.5" /> Edit</button><button onClick={() => remove(item)} className="grid h-9 w-9 place-items-center rounded-xl border border-destructive/30 text-destructive"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>}
    <Modal open={open} onClose={() => setOpen(false)} title={form.client_id ? 'Edit Trusted Client' : 'Add Trusted Client'}><form onSubmit={save} className="space-y-4"><input required className={field} placeholder="Client or organization name" value={form.name || ''} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className={field} type="url" placeholder="Website URL (optional)" value={form.website_url || ''} onChange={(e) => setForm({ ...form, website_url: e.target.value })} /><input className={field} placeholder="Accessible logo description" value={form.alt_text || ''} onChange={(e) => setForm({ ...form, alt_text: e.target.value })} /><button type="button" onClick={() => fileRef.current?.click()} className="flex min-h-24 w-full flex-col items-center justify-center rounded-xl border border-dashed border-primary/40 bg-primary/5 text-sm font-bold text-primary"><ImageUp className="mb-2 h-6 w-6" />{file ? file.name : form.has_logo ? 'Replace logo' : 'Choose PNG, JPEG, or WebP logo'}<span className="mt-1 text-xs font-normal text-muted-foreground">Maximum 2 MB</span></button><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setFile(e.target.files?.[0] || null)} /><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={Boolean(form.is_active)} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} /> Published</label><button disabled={saving || (!form.client_id && !file)} className="btn-gold w-full disabled:opacity-50">{saving ? 'Saving…' : 'Save Trusted Client'}</button></form></Modal>
  </div>;
}
